### ISSUE TITLE
Не работает построение друзей

### ISSUE THREAD

**Issue by disovi** [danumeric/vk-api-vue#1]
![image](https://user-images.githubusercontent.com/705617/174287735-a3b50dfb-9318-4bf0-81df-6ccee180ff4d.png)

**Comment by disovi** [comment]
![image](https://user-images.githubusercontent.com/705617/174287923-fa37ef15-be13-4f95-89ba-11ada9ca356e.png)

в инкогнито такая ошибка

**Comment by danumeric** [comment]
Не было обработки ошибки при парсинге друзей у закрытых профилей. Добавлено. 
https://github.com/danumeric/vk-api-vue/commit/843738549278f7a3045b7d09dffb39f47aade202

**Comment by disovi** [comment]
@danumeric не похоже, что дело в этом, поскольку у пользователей со скриншота друзья открыты. Более того, даже по предустановленным профилям по нажатию на кнопку построить список друзей ничего не происходит (пробовал и chrome и firefox). Быть может тут старая версия? http://dan-api-vk.herokuapp.com/

**Comment by danumeric** [comment]
К сожалению воспроизвести баг не удалось . 
Возможные проблемы: 
1) не выбраны пользователи для построения списка друзей в левой колонке - должны быть выделены тёмно-зеленым ( это реализовано согласно заданию); 
2) открыто более 2 клиентов -  так как в демо версии используется 1 токен на всех клиентов веб приложения, но тогда ошибка будет "Too many requests per second".

**Comment by disovi** [comment]
@danumeric прошу прощения, всё работает :+1:  первый раз увидел такую трактовку задания)
